create table sensor (
    id int generated by default as identity primary key,
    name varchar(30) unique not null
);

create table measurement (
    id int generated by default as identity primary key,
    value numeric(5,2) not null,
    raining boolean not null,
    created_at timestamp not null,
    sensor_id int references sensor(id) on delete cascade
);